version: '3.9'
services:
  es01:

    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es01
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx2g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticData:/usr/share/elasticsearch/data
      - elasticsearch:/usr/share/elasticsearch
      # - /path/to/elastic/storage:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - ELASTICSEARCH_URL="http://es01:9200"
      - ELASTICSEARCH_HOSTS="http://es01:9200"
    networks:
      - elastic
      
  logstash:
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    container_name: logstash01
    ports:
     - "5000:5000"
     - "9600:9600"
     - "5044:5044"
    environment:
     - LS_JAVA_OPTS:"-Xms256m"
     - http.host:"0.0.0.0"
     - xpack.monitoring.elasticsearch.hosts:["http://es01:9200"]
     - xpack.monitoring.enabled:true
     - xpack.monitoring.elasticsearch.username:elastic
     - xpack.monitoring.elasticsearch.password:$ELASTIC_PASSWORD
    volumes:
     - logstash:/usr/share/logstash/
     #- ~/settings/:/usr/share/logstash/config/
     #- ~/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
     #- ~/pipeline/:/usr/share/logstash/pipeline/
    networks:
     - elastic
    depends_on:
     - es01

volumes:
  elasticData:
    driver: local
  logstash:
    driver: local
  elasticsearch:
    driver: local

networks:
  elastic:
    driver: bridge
  
